apiVersion: skaffold/v2beta9
kind: Config
profiles:
- name: metrics-provider-local
  build:
    artifacts:
    - image: registry.container-registry:5000/artemis-ext-scaler
      context: ./metrics-provider
      kaniko:
        dockerfile: Dockerfile
        image: gcr.io/kaniko-project/executor:debug-v1.3.0
        cache:
          repo: registry.container-registry:5000/artemis-ext-scaler
          hostPath: /home/thor/data
    insecureRegistries:
    - registry.container-registry:5000
    cluster:
      namespace: artemis
      dockerConfig:
        secretName: regcred
  deploy:
    kubectl:
      manifests:
      - k8s-manifest/artemis/deployment.yaml
- name: metrics-provider
  build:
    artifacts:
    - image: balchu/artemis-ext-scaler
      context: ./metrics-provider
      kaniko:
        dockerfile: Dockerfile
        cache:
          repo: balchu/artemis-ext-scaler
    cluster:
      namespace: artemis
      dockerConfig:
        secretName: regcred
  deploy:
    kubectl:
      manifests:
      - k8s-manifest/artemis/deployment.yaml
- name: consumer
  build:
    artifacts:
    - image: balchu/artemis-consumer
      context: ./consumer
      jib: {}
    local:
      push: true
  deploy:
    kubectl:
      manifests:
      - k8s-manifest/consumer-deployment.yaml
