artemis:
  host: ${ARTEMIS_SERVER_HOST:10.152.183.203}
  port: ${ARTEMIS_SERVER_PORT:61616}
  user: ${ARTEMIS_USERNAME:artemis}
  password: ${ARTEMIS_PASSWORD:artemis}

logging:
  level:
    root: WARN
    org.bal: INFO